controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robotnik_base_controller:
      type: diff_drive_controller/DiffDriveController

robotnik_base_controller:
  ros__parameters:
    left_wheel_names:
      - summit_xl_front_left_wheel_joint
      - summit_xl_back_left_wheel_joint
    right_wheel_names:
      - summit_xl_front_right_wheel_joint
      - summit_xl_back_right_wheel_joint
      
    wheel_separation: 0.470
    wheel_radius: 0.11

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    base_frame_id: summit_xl_base_footprint
    odom_frame_id: summit_xl_odom
    enable_odom_tf: true
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.25

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0
        min_velocity: -3.0
        has_acceleration_limits: true
        max_acceleration: 6.0
        min_acceleration: -6.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 6.0
        has_acceleration_limits: true
        max_acceleration: 6.0
